source :rubygems
gem "diff-lcs", "~>1.1.2"
gem "cucumber", "~>1.2.1"
gem "selenium-webdriver", "~>2.22.2"
gem "rspec", "~>2.6.0"
gem "selenium-client", "~> 1.2.18"
gem "capybara", "~> 1.1.2"
gem "yard", "~>0.8.1"
gem "yard-cucumber", "~> 2.1.7"
gem "viewcumber", "~>0.3.1"
gem "rake", "~>0.9.2.2"
gem "logger"
gem "capybara-screenshot", "0.2.2"
gem "syntax", "~> 1.0.0"
gem "show_me_the_cookies"
gem "active_support", "~> 3.0.0"